---
title: "R Notebook"
output: html_notebook
---

Missing IEIN Numbers: ALL
```{r}
primary_missing_iein <- 
  isbe_report_primary_midyear_2020_full %>%
  select(`Teacher Last Name`, 
         `Teacher First Name`, 
         `Teacher Birth Date`, 
         `Teacher IEIN  (Illinois Educator Identification Number)`) %>%
  filter(is.na(`Teacher IEIN  (Illinois Educator Identification Number)`)) %>%
  distinct()

middle_missing_iein <- 
  isbe_report_middle_midyear_2020_full %>%
  select(`Teacher Last Name`, 
         `Teacher First Name`, 
         `Teacher Birth Date`, 
         `Teacher IEIN  (Illinois Educator Identification Number)`) %>%
  filter(is.na(`Teacher IEIN  (Illinois Educator Identification Number)`)) %>%
  distinct()

missing_iein_full <- 
  bind_rows(primary_missing_iein, 
            middle_missing_iein) %>%
  distinct()

# write.csv(missing_iein_full, "missing_iein_19-20_midyear_report.csv")
```

Missing Teacher Birthdays: ALL
```{r}
primary_missing_teacher_birthday <- 
  isbe_report_primary_midyear_2020_full %>%
  select(`Teacher Last Name`, 
         `Teacher First Name`, 
         `Teacher Birth Date`) %>%
  distinct() %>%
  filter(is.na(`Teacher Birth Date`))

middle_missing_teacher_birthday <- 
  isbe_report_middle_midyear_2020_full %>%
  select(`Teacher Last Name`, 
         `Teacher First Name`, 
         `Teacher Birth Date`) %>%
  distinct() %>%
  filter(is.na(`Teacher Birth Date`))

missing_birthday_teacher_full <- 
  bind_rows(middle_missing_teacher_birthday, 
            primary_missing_teacher_birthday) %>%
  distinct()

write.csv(missing_birthday_teacher_full, 
          "missing_teacher_birthday_19-20_midyear_report.csv", 
          row.names = FALSE)

```

List of teachers that work in multiple schools

```{r}

```

